name: music_player_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  google_fonts: ^6.1.0
  audioplayers: ^5.2.1
  flutter_svg: ^2.0.9
  get: ^4.6.6
  lottie: ^3.1.0
  shimmer_pro: ^0.0.6
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"

flutter:
  uses-material-design: true
  assets:
     - assets/